version: '3.8'

services:
  ms-alertas:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DJANGO_SECRET_KEY=ms-alertas-secret-sprint4
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=biteco_alerts
      - JWT_SECRET=biteco-secret-sprint4
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_alertas_data:/data/db

volumes:
  mongo_alertas_data:
